version: '3.7'

services:
  exo-gui:
    container_name: exo-gui-cn
    build:
      context: .
      dockerfile: DockerFile
    image: exo-gui:1.0
    volumes: 
      - './:/app'
      - '/app/node_modules'
    ports:
      - '8280:8280'
    command: "npm run dev"
